[pytest]
# Tell pytest to look for files that start with "Test" (capital T) 
python_files = Test*.py test_*.py *_test.py

# Tell pytest to show print statements in the console
addopts = -s

# If you ALSO want to name your functions differently, uncomment the line below:
# python_functions = check_* test_*